In [86]:
import numpy as np
import csv # works with csv file

height = []
weight = []
with open('baseball.csv' , 'r') as f:
    reader = csv.reader(f)
    rownum = 0
    for row in reader:
        if(rownum >= 1):
            height.append(row[3])
            weight.append(row[4])
            #bmi = int(row[3]) / int(row[4]) ** 2
            #height.append(bmi)
        rownum = rownum + 1
#print(height)
#print(weight)
np_height = np.array(height)
np_weight = np.array(weight)
np_height = np_height.astype(np.float32 , copy = False)
np_weight = np_weight.astype(np.float32 , copy = False)
bmi = np_height / np_weight ** 2
#print(bmi)

#both index are inclusive
newarray = height[100:200]
print(newarray)

#
#logical and
#logical or
#logical not

x = np.array([10,20,30,40])
x > 20
print(np.logical_and(x > 20 , x < 35))
print(np.logical_or(x > 20 , x < 35))
print(np.logical_not(x > 20 , x < 35))
for i in np.nditer(x):
    print(i)

array1 = np.array([[1,3],
                [2,4]])
#array1
#array1.shape
#array1[0,1]
#array1[1]
array1[:,0]

        
#with open('baseball.csv', newline='') as csvfile:
#    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
#    for row in spamreader:
#         print(', '.join(row))

['73', '74', '72', '73', '69', '72', '73', '75', '75', '73', '72', '72', '76', '74', '72', '77', '74', '77', '75', '76', '80', '74', '74', '75', '78', '73', '73', '74', '75', '76', '71', '73', '74', '76', '76', '74', '73', '74', '70', '72', '73', '73', '73', '73', '71', '74', '74', '72', '74', '71', '74', '73', '75', '75', '79', '73', '75', '76', '74', '76', '78', '74', '76', '72', '74', '76', '74', '75', '78', '75', '72', '74', '72', '74', '70', '71', '70', '75', '71', '71', '73', '72', '71', '73', '72', '75', '74', '74', '75', '73', '77', '73', '76', '75', '74', '76', '75', '73', '71', '76']
[False False  True False]
[ True  True  True  True]
[ True  True False False]
10
20
30
40


array([1, 2])

In [101]:
x = [[1,2],[3,4]]
y = np.array(x)
z = np.array([[1,2],[3,4]])
print(y + z)
print(x + z)
print(y * z)
conversion = np.array[0.1,0.2,0.3]
print(x * conversion)

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [58]:
import csv
with open('sample.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['header1', 'header2' , 'header3'])
    writer.writerow(['data1', 'data2', 'data3'])
